### ISSUE TITLE
Dockerfile missing dependency?   latke.props ?

### ISSUE THREAD

**Issue by creditket** [88250/symphony#85]
### 描述问题 Describe the problem

after cloning the repo and building the with the Dockerfile as:

```
git clone https://github.com/88250/symphony.git && cd symphony
docker build -t symphony . 
docker run -d --name symphony_container symphony

docker run -d --name symphony_container symphony          
1a64c9ad69526e8ca7c7b93136825709b18f37c071a60c53ff7d8a6607159b8c
x@xnoMacBook-Pro symphony % docker logs 1a64c9ad69526e8ca7c7b93136825709b18f37c071a60c53ff7d8a6607159b8c
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/opt/sym/lib/log4j-slf4j-impl-2.20.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
[WARN ]-[2024-02-08 05:45:56]-[org.b3log.latke.Latkes:713]: !!!!Runtime mode is [DEVELOPMENT], please make sure configured it with [PRODUCTION] in latke.properties if deployed on production environment!!!!
[ERROR]-[2024-02-08 05:45:56]-[org.b3log.symphony.Server:123]: Latke init failed, please configure latke.props or run with args, visit https://ld246.com/article/1492881378588 for more details
```
http://localhost:8080/symphony

```
This site can’t be reachedlocalhost refused to connect.
Try:
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED
```

### 期待的结果 Expected result

<img width="968" alt="image" src="https://github.com/88250/symphony/assets/93809455/55b201cd-6272-47e0-87d0-50352ab4d768">

### 版本环境 Version environment

* 版本 Version：[symphony-v3.6.4.zip](https://github.com/88250/symphony/releases/download/v3.6.4/symphony-v3.6.4.zip)?
* 操作系统 Operating system： mac
* 浏览器（如果使用）Browser (if used)：Chrome Version 121.0.6167.85 (Official Build) (x86_64)

**Comment by creditket** [comment]
also

```
docker pull b3log/symphony 
docker run --detach --name sym --network=host \
    --env RUNTIME_DB="MYSQL" \
    --env JDBC_USERNAME="root" \
    --env JDBC_PASSWORD="123456" \
    --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" \
    --env JDBC_URL="jdbc:mysql://127.0.0.1:3306/symphony?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC" \
    b3log/symphony --listen_port=8080 --server_scheme=http --server_host=localhost --server_port=
```

when 

```
mysql -u root -p
Enter password: 123456
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 26
Server version: 8.1.0 Homebrew

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

But

```
[ERROR]-[2024-02-08 13:00:23]-[org.b3log.latke.repository.jdbc.util.JdbcRepositories:281]: Creates table [symphony_emotion] error
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

[ERROR]-[2024-02-08 13:00:24]-[org.b3log.latke.repository.jdbc.JdbcRepository:650]: Failed to initialize JDBC transaction
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

[ERROR]-[2024-02-08 13:00:24]-[org.b3log.symphony.service.InitMgmtService:690]: Initializes Sym failed
java.lang.IllegalStateException: Begin a transaction failed

	at org.b3log.latke.repository.jdbc.JdbcRepository.beginTransaction(JdbcRepository.java:652) ~[latke-core-3.4.30.jar:?]
	at org.b3log.latke.repository.AbstractRepository.beginTransaction(AbstractRepository.java:160) ~[latke-core-3.4.30.jar:?]
	at org.b3log.symphony.service.InitMgmtService.initSym(InitMgmtService.java:250) [sym/:?]
	at org.b3log.symphony.service.InitMgmtService_$$_jvst571_9b._d5initSym(InitMgmtService_$$_jvst571_9b.java) [sym/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:108) [latke-core-3.4.30.jar:?]
	at org.b3log.symphony.service.InitMgmtService_$$_jvst571_9b.initSym(InitMgmtService_$$_jvst571_9b.java) [sym/:?]
	at org.b3log.symphony.Server.main(Server.java:170) [sym/:?]
```

**Comment by 88250** [comment]
建议排查一下数据卷挂载是否正确。
